FROM golang:alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build and run the binary every time the container starts
ENTRYPOINT ["sh", "-c", "cd services/auth && go build -o auth-service . && ./auth-service"]
