version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: signage_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: signage_user
      POSTGRES_PASSWORD: signage_pass
      POSTGRES_DB: signage_dev
    ports:
      - "5432:5432"
    volumes:
      - signage_pgdata:/var/lib/postgresql/data

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile.dev
    container_name: auth-service-dev
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    volumes:
      - .:/app

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - auth

volumes:
  signage_pgdata:
