-- +migrate Down

DROP TABLE IF EXISTS SessionLog;
DROP TABLE IF EXISTS UserRoleAssignment;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Permission;
DROP TABLE IF EXISTS RolePermission;
DROP TABLE IF EXISTS UserProfile;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Business;
DROP EXTENSION IF EXISTS "pgcrypto";